Repository runabol/tork, pull requests merged in 2025-06, with the labels that each got.

#539 chore: Updated web service in docker compose
  docker-compose.yaml
Labels: 🧹 Updates

#541 Fix: close events subscription
  broker/rabbitmq.go
Labels: 🐛 Bug

#542 Fix: unwrapping errors
  runtime/docker/docker.go
  runtime/docker/docker_test.go
Labels: 🐛 Bug

#546 Fix: Remove bad image on verification failure
  runtime/docker/docker.go
  runtime/docker/docker_test.go
Labels: 🐛 Bug, 🧹 Updates

#547 Improved image pruning
  runtime/docker/docker.go
  runtime/docker/docker_test.go
Labels: 🧹 Updates
